# Generated by Django 6.0.5 on 2026-05-26 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_plan_customuser_date_of_birth_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
    ]
