# Generated by Django 6.0.5 on 2026-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_enquiry_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_qr',
            field=models.ImageField(blank=True, help_text='UPI payment QR code image', null=True, upload_to='payment_qr/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (watch link or shorts link)'),
        ),
    ]
