# Generated by Django 6.0.5 on 2026-05-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_organization_payment_qr_organization_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='payment_qr',
        ),
    ]
