# Generated by Django 6.0.5 on 2026-05-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_organization_payment_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='youtube_url',
        ),
    ]
