# Generated by Django 6.0.5 on 2026-05-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_organization_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='visiting_card',
            field=models.FileField(blank=True, null=True, upload_to='visiting_cards/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
