# Generated by Django 6.0.5 on 2026-05-27 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_organization_payment_qr_organization_visiting_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='payment_qr',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='visiting_card',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='youtube_url',
        ),
    ]
