# Generated by Django 6.0.5 on 2026-05-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_organization_payment_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram post URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='pdf_catalog',
            field=models.FileField(blank=True, help_text='Downloadable PDF catalog', null=True, upload_to='catalogs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs_json',
            field=models.JSONField(blank=True, default=dict, help_text='Key-value product specifications'),
        ),
        migrations.AddField(
            model_name='product',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube demo video URL'),
        ),
    ]
