# Generated by Django 6.0.5 on 2026-05-29 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_instagram_url_product_pdf_catalog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('subdomain', models.SlugField(blank=True, help_text='Pre-assigned subdomain (optional)', max_length=100, null=True)),
                ('site_title', models.CharField(blank=True, max_length=200)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.businesscategory')),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation', to='app.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.plan')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Pay Now', max_length=100)),
                ('method', models.CharField(choices=[('upi', 'UPI (GPay / PhonePe / Paytm)'), ('bank', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('other', 'Other')], default='upi', max_length=20)),
                ('upi_id', models.CharField(blank=True, help_text='e.g. business@okicici', max_length=100)),
                ('qr_image', models.ImageField(blank=True, help_text='Upload QR image from your payment app', null=True, upload_to='payment_qr/')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_qrs', to='app.organization')),
            ],
            options={
                'ordering': ['order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='SupplyChainRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('dealer', 'Dealer / Wholesaler'), ('retailer', 'Retailer / Reseller'), ('service_agency', 'Service Agency'), ('technician', 'Technician'), ('freelancer', 'Freelancer'), ('customer', 'Customer')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='diagram-3', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#2563eb', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_parent_roles', models.ManyToManyField(blank=True, help_text='Which roles are allowed as parent of this role', related_name='allowed_child_roles', to='app.supplychainrole')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='supply_chain_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='app.supplychainrole'),
        ),
        migrations.CreateModel(
            name='VisitingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('bold', 'Bold'), ('minimal', 'Minimal'), ('gradient', 'Gradient')], default='modern', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='visiting_cards/')),
                ('direct_phone', models.CharField(blank=True, max_length=20)),
                ('direct_whatsapp', models.CharField(blank=True, max_length=20)),
                ('direct_email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_saves', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_card', to='app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(help_text='With country code, e.g. 919876543210', max_length=20)),
                ('greeting_message', models.TextField(default="Hi! I found your business on Portal and I'd like to enquire.", help_text='Pre-filled WhatsApp message when customer taps the button')),
                ('show_float_button', models.BooleanField(default=True, help_text='Floating WhatsApp button on landing page')),
                ('show_in_enquiry_form', models.BooleanField(default=True, help_text='Show WA button after form submission')),
                ('business_hours_only', models.BooleanField(default=False, help_text='Only show button during working hours')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyChainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_chain_parents', to='app.organization')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_chain_children', to='app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
