# Generated by Django 6.0.5 on 2026-06-01 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInviteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points_per_invite', models.PositiveIntegerField(default=50, help_text='OrgPoints awarded to the inviting org when their invitee joins.')),
                ('max_invites_trial', models.PositiveIntegerField(default=2, help_text='Trial plan: max invites allowed')),
                ('max_invites_silver', models.PositiveIntegerField(default=5, help_text='Silver plan: max invites allowed')),
                ('max_invites_gold', models.PositiveIntegerField(default=20, help_text='Gold plan: max invites allowed')),
                ('max_invites_platinum', models.PositiveIntegerField(default=100, help_text='Platinum plan: max invites allowed')),
                ('allow_member_invites', models.BooleanField(default=True, help_text='Master switch — disable to prevent all member-to-member invites.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member Invite Configuration',
                'verbose_name_plural': 'Member Invite Configuration',
            },
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='bonus_rewarded',
            field=models.BooleanField(default=False, help_text='True once the referral bonus has been credited.'),
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='invite_bonus_points',
            field=models.PositiveIntegerField(default=0, help_text='OrgPoints to award to referred_by_org when this invite is accepted.'),
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='invite_type',
            field=models.CharField(choices=[('admin', 'Admin Invite'), ('member', 'Member Invite')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='referred_by_org',
            field=models.ForeignKey(blank=True, help_text='Set when a member org sends the invite (for bonus tracking).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_member_invitations', to='app.organization'),
        ),
    ]
