# Generated by Django 6.0.5 on 2026-06-03 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_memberinviteconfig_invitationtoken_bonus_rewarded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquirySLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_sla_hours', models.PositiveIntegerField(default=24, help_text='Hours after creation before an enquiry is flagged ⚠ Overdue')),
                ('escalation_sla_hours', models.PositiveIntegerField(default=48, help_text='Hours after creation before an enquiry is flagged 🔴 Escalated')),
                ('auto_set_due_date', models.BooleanField(default=True, help_text='Automatically set response_due_by on enquiry create / reassign')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enquiry SLA Configuration',
                'verbose_name_plural': 'Enquiry SLA Configuration',
            },
        ),
        migrations.AddField(
            model_name='enquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Currently handling org — may differ from original after reassignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to='app.organization'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_reassigned',
            field=models.BooleanField(default=False, help_text='True if this enquiry has ever been reassigned'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Last time status changed or a note was added', null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='response_due_by',
            field=models.DateTimeField(blank=True, help_text='SLA deadline for first response', null=True),
        ),
        migrations.CreateModel(
            name='EnquiryReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Reason for reassignment (e.g. "Org not responding for 48h")')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='app.enquiry')),
                ('from_org', models.ForeignKey(help_text='Organisation that previously held this enquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_given_away', to='app.organization')),
                ('reassigned_by', models.ForeignKey(help_text='Super Admin who performed the reassignment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_org', models.ForeignKey(help_text='Organisation this enquiry was reassigned to', on_delete=django.db.models.deletion.CASCADE, related_name='enquiries_received', to='app.organization')),
            ],
            options={
                'verbose_name': 'Enquiry Reassignment',
                'verbose_name_plural': 'Enquiry Reassignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
