# Generated by Django 6.0.5 on 2026-06-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_enquiryslaconfig_enquiry_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryreassignment',
            name='enquiry',
        ),
        migrations.RemoveField(
            model_name='enquiryreassignment',
            name='from_org',
        ),
        migrations.RemoveField(
            model_name='enquiryreassignment',
            name='reassigned_by',
        ),
        migrations.RemoveField(
            model_name='enquiryreassignment',
            name='to_org',
        ),
        migrations.DeleteModel(
            name='EnquirySLAConfig',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='is_reassigned',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='last_activity_at',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='response_due_by',
        ),
        migrations.DeleteModel(
            name='EnquiryReassignment',
        ),
    ]
