# Generated by Django 6.0.5 on 2026-06-04 05:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_enquiryreassignment_enquiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enquiry_submit', 'Enquiry Submitted'), ('whatsapp_click', 'WhatsApp Button Click'), ('phone_click', 'Phone Number Click'), ('product_view', 'Product Viewed'), ('service_view', 'Service Viewed'), ('vcard_download', 'vCard Downloaded'), ('payment_qr_view', 'Payment QR Viewed'), ('cart_add', 'Item Added to Cart'), ('cart_checkout', 'Cart Checkout')], db_index=True, max_length=30)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_name', models.CharField(blank=True, max_length=200)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'event_type', 'created_at'], name='app_analyti_organiz_2923af_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=16)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='app_pagevie_organiz_a6a256_idx')],
            },
        ),
    ]
