# Generated by Django 6.0.4 on 2026-06-09 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_analyticsevent_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationtoken',
            name='approval_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason shown to the applicant when rejected.'),
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
    ]
