# Generated by Django 6.0.4 on 2026-06-10 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('whatsapp_click', 'WhatsApp Button Click'), ('enquiry_submit', 'Enquiry Submitted'), ('new_member', 'New Member Joined')], db_index=True, default='whatsapp_click', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
